- name: Configure dotfiles
  hosts: all
  vars:
    home: "{{ ansible_env.HOME }}"
  roles:
    - { role: ../roles/neovim }
    - { role: ../roles/tmux }
    - { role: ../roles/alacritty }
    - { role: ../roles/zsh }
    - { role: ../roles/profile }
